id: P820C42CF
initial_creation_type: input
source_metadata:
  title: Kashmiri Śākyaśrībhadra
  language: de
  description: 'Texts by and about the Kashmiri master Śākyaśrībhadra (shā kya shrī
    bzang po, 1127–1225), who in 1204 travelled to Tibet, where he became the teacher
    of a number of important lamas, including Sakya Paṇḍita Kunga Gyaltsen:'
  volume:
    15471f0b0f154a23828d55864433f730:
      title: An Instruction on Pure View and Conduct
      parent: Instructions
    98004f9c76964384afe836d6e61df4ce:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Practices
    b6bcd6859c264bf5ae2019142d590e8b:
      title: Taking the Vows of Sojong
      parent: Practices
    c4c4f79ea3804d298801c0d529aaf8e8:
      title: The Seven Branches for Practising the Sacred Dharma
      parent: Practices
    9e313775a13e49d08b3f94db270e7638:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
created_at: '2022-03-01T02:21:09.310818'
last_modified_at: '2022-03-01T02:21:09.310821'
